/**
 * Unified Skins - Generated by Migration Script
 * 
 * This file contains all consolidated skin definitions from both the old and new systems.
 * Generated on: 2025-09-29T00:41:22.721Z
 * 
 * DO NOT EDIT MANUALLY - Use the migration script instead.
 */

export interface UnifiedSkin {
  id: string;
  name: string;
  tier: "common" | "uncommon" | "rare" | "legendary" | "epic" | "mythic" | "event";
  source: "production" | "inspiration" | "pre-production";
  kind: "solid" | "animated" | "patterned";
  colors: string[];
  base: {
    fill: string;
    stroke: string;
    shine: string;
  };
  pattern: {
    type: string;
    colors?: string[];
    [key: string]: any;
  };
  anim: string;
  migratedFrom?: "old" | "new" | "merge";
  bio?: string;
  origin?: {
    type: string;
    source: string;
    displayName: string;
  };
  tags?: string[];
}

export const SKINS: Record<string, UnifiedSkin> = {
  acorn: {
  "id": "acorn",
  "name": "Acorn",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#a16207"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  acorn_enhanced: {
  "id": "acorn_enhanced",
  "name": "Acorn Enhanced",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#a16207"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  apple_shine: {
  "id": "apple_shine",
  "name": "Apple Shine",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#f97316"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  apple_shine_enhanced: {
  "id": "apple_shine_enhanced",
  "name": "Apple Shine Enhanced",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#f97316"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  aurora: {
  "id": "aurora",
  "name": "Aurora",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#8b5cf6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  blueberry: {
  "id": "blueberry",
  "name": "Blueberry",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#60a5fa"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  blueberry_legacy: {
  "id": "blueberry_legacy",
  "name": "Blueberry (Legacy)",
  "tier": "common",
  "source": "inspiration",
  "kind": "solid",
  "colors": [
    "#60a5fa"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "new"
},

  blueberry_enhanced: {
  "id": "blueberry_enhanced",
  "name": "Blueberry Enhanced",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#60a5fa"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  bluebird: {
  "id": "bluebird",
  "name": "Bluebird",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#60a5fa"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  bluebird_enhanced: {
  "id": "bluebird_enhanced",
  "name": "Bluebird Enhanced",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#60a5fa"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  bubblegum: {
  "id": "bubblegum",
  "name": "Bubblegum",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#f472b6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  bubblegum_insp: {
  "id": "bubblegum_insp",
  "name": "Bubblegum (Inspiration)",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#f472b6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  charcoal: {
  "id": "charcoal",
  "name": "Charcoal",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#2A2F35"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  cherry: {
  "id": "cherry",
  "name": "Cherry",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#dc2626"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  coral: {
  "id": "coral",
  "name": "Coral",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#FF8B7A"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  fog: {
  "id": "fog",
  "name": "Fog",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#9CA3AF"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  fog_enhanced: {
  "id": "fog_enhanced",
  "name": "Fog Enhanced",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#9CA3AF"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  grape: {
  "id": "grape",
  "name": "Grape",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#8b5cf6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  green: {
  "id": "green",
  "name": "Green",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#22c55e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  green_legacy: {
  "id": "green_legacy",
  "name": "Green (Legacy)",
  "tier": "common",
  "source": "inspiration",
  "kind": "solid",
  "colors": [
    "#22c55e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "new"
},

  green_enhanced: {
  "id": "green_enhanced",
  "name": "Green Enhanced",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#22c55e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  honey: {
  "id": "honey",
  "name": "Honey",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#fbbf24"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  honey_enhanced: {
  "id": "honey_enhanced",
  "name": "Honey Enhanced",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#fbbf24"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  lava: {
  "id": "lava",
  "name": "Lava",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#dc2626"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  lilac: {
  "id": "lilac",
  "name": "Lilac",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#BDA7FF"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  lilac_enhanced: {
  "id": "lilac_enhanced",
  "name": "Lilac Enhanced",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#BDA7FF"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  mint: {
  "id": "mint",
  "name": "Mint",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#4ade80"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  mint_legacy: {
  "id": "mint_legacy",
  "name": "Mint (Legacy)",
  "tier": "common",
  "source": "inspiration",
  "kind": "solid",
  "colors": [
    "#4ade80"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "new"
},

  mint_enhanced: {
  "id": "mint_enhanced",
  "name": "Mint Enhanced",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#4ade80"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  moss: {
  "id": "moss",
  "name": "Moss",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#5BA86D"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  seafoam: {
  "id": "seafoam",
  "name": "Seafoam",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#14b8a6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sky: {
  "id": "sky",
  "name": "Sky",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#A9D8FF"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  slate: {
  "id": "slate",
  "name": "Slate",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#64748b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  tangerine: {
  "id": "tangerine",
  "name": "Tangerine",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#f97316"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  tangerine_insp: {
  "id": "tangerine_insp",
  "name": "Tangerine (Inspiration)",
  "tier": "common",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#f97316"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  acorn_buddy: {
  "id": "acorn_buddy",
  "name": "Acorn Buddy",
  "tier": "uncommon",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#6c8a3a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  acorn_buddy_enhanced: {
  "id": "acorn_buddy_enhanced",
  "name": "Acorn Buddy Enhanced",
  "tier": "uncommon",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#6c8a3a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  autumn_fade: {
  "id": "autumn_fade",
  "name": "Autumn Fade",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#22c55e",
    "#dc2626"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  berry_fizz: {
  "id": "berry_fizz",
  "name": "Berry Fizz",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#FF6BA0",
    "#7D4AA3"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  blue_lagoon: {
  "id": "blue_lagoon",
  "name": "Blue Lagoon",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#68E0FF",
    "#3D78C1"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  blue_lagoon_enhanced: {
  "id": "blue_lagoon_enhanced",
  "name": "Blue Lagoon Enhanced",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#68E0FF",
    "#3D78C1"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  candy_corn: {
  "id": "candy_corn",
  "name": "Candy Corn",
  "tier": "uncommon",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#ff6b00",
    "#ffd700",
    "#ffffff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  citrus_pop: {
  "id": "citrus_pop",
  "name": "Citrus Pop",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fef08a",
    "#84cc16"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  cotton_candy: {
  "id": "cotton_candy",
  "name": "Cotton Candy",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#60a5fa",
    "#f472b6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  drift_puff: {
  "id": "drift_puff",
  "name": "Drift Puff",
  "tier": "uncommon",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#bfe7f4",
    "#ffffff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  foam_crest: {
  "id": "foam_crest",
  "name": "Foam Crest",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#74b7e4",
    "#e9f7ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  forest_mist: {
  "id": "forest_mist",
  "name": "Forest Mist",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#5BA86D",
    "#E4EEE7"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ice_cream_swirl: {
  "id": "ice_cream_swirl",
  "name": "Ice Cream Swirl",
  "tier": "uncommon",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#ffffff",
    "#8b4513"
  ],
  "base": {
    "fill": "#ffffff",
    "stroke": "#1f2937",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "static_swirl",
    "colors": [
      "#ffffff",
      "#8b4513"
    ],
    "rotation": false,
    "intensity": 0.9
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ice_cream_swirl_2: {
  "id": "ice_cream_swirl_2",
  "name": "Ice Cream Swirl 2",
  "tier": "uncommon",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#ffffff",
    "#8b4513"
  ],
  "base": {
    "fill": "#ffffff",
    "stroke": "#1f2937",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "conic_gradient",
    "colors": [
      "#ffffff",
      "#8b4513"
    ],
    "rotation": false,
    "intensity": 0.9
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ice_cream_swirl_3: {
  "id": "ice_cream_swirl_3",
  "name": "Ice Cream Swirl 3",
  "tier": "uncommon",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#ffffff",
    "#8b4513"
  ],
  "base": {
    "fill": "#ffffff",
    "stroke": "#1f2937",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "logarithmic_spiral",
    "colors": [
      "#ffffff",
      "#8b4513"
    ],
    "rotation": false,
    "intensity": 0.9
  },
  "anim": "none",
  "migratedFrom": "old"
},

  incense_drift: {
  "id": "incense_drift",
  "name": "Incense Drift",
  "tier": "uncommon",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#b79f80",
    "#f0e7d8"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  leaf_fade: {
  "id": "leaf_fade",
  "name": "Leaf Fade",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#22c55e",
    "#16a34a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ocean_mist: {
  "id": "ocean_mist",
  "name": "Ocean Mist",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#0ea5e9",
    "#bae6fd"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  quench_mist: {
  "id": "quench_mist",
  "name": "Quench Mist",
  "tier": "uncommon",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#2a2a2a",
    "#5f6a71"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  rainbow: {
  "id": "rainbow",
  "name": "Rainbow",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#ef4444",
    "#f97316",
    "#fbbf24",
    "#22c55e",
    "#3b82f6",
    "#6366f1",
    "#8b5cf6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  raindrop: {
  "id": "raindrop",
  "name": "Raindrop",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#e0e7ff",
    "#6366f1"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  raindrop_enhanced: {
  "id": "raindrop_enhanced",
  "name": "Raindrop Enhanced",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#e0e7ff",
    "#6366f1"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  rose_glow: {
  "id": "rose_glow",
  "name": "Rose Glow",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#f43f5e",
    "#fb7185"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sea_breeze: {
  "id": "sea_breeze",
  "name": "Sea Breeze",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#67e8f9",
    "#0ea5e9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sea_breeze_enhanced: {
  "id": "sea_breeze_enhanced",
  "name": "Sea Breeze Enhanced",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#67e8f9",
    "#0ea5e9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  shell_gleam: {
  "id": "shell_gleam",
  "name": "Shell Gleam",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#8de3de",
    "#f6ffff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  spring_fade: {
  "id": "spring_fade",
  "name": "Spring Fade",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#B7F8C6",
    "#FFF4A8"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  spring_fade_enhanced: {
  "id": "spring_fade_enhanced",
  "name": "Spring Fade Enhanced",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#B7F8C6",
    "#FFF4A8"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sun_drum: {
  "id": "sun_drum",
  "name": "Sun Drum",
  "tier": "uncommon",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#ffcc66",
    "#fff3cc"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sunrise: {
  "id": "sunrise",
  "name": "Sunrise",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#2196F3",
    "#64B5F6",
    "#FFEB3B",
    "#FF9800",
    "#F44336"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sunset: {
  "id": "sunset",
  "name": "Sunset",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#8b5cf6",
    "#ec4899",
    "#f97316",
    "#fbbf24"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sunset_beach: {
  "id": "sunset_beach",
  "name": "Sunset Beach",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#f97316",
    "#fbbf24",
    "#f472b6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  swallow_sweep: {
  "id": "swallow_sweep",
  "name": "Swallow Sweep",
  "tier": "uncommon",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#cf7e50",
    "#f4c4a2"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  tide_glass: {
  "id": "tide_glass",
  "name": "Tide Glass",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#78d3d0",
    "#e9fbfb"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  twilight: {
  "id": "twilight",
  "name": "Twilight",
  "tier": "uncommon",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#6366f1",
    "#8b5cf6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  watermelon: {
  "id": "watermelon",
  "name": "Watermelon",
  "tier": "uncommon",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#90ee90",
    "#ffffff",
    "#ff69b4"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  aftershock: {
  "id": "aftershock",
  "name": "Aftershock",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#111827",
    "#374151"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  anemone_wiggle: {
  "id": "anemone_wiggle",
  "name": "Anemone Wiggle",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#ff9ea0"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ashfall: {
  "id": "ashfall",
  "name": "Ashfall",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#9a3412",
    "#7c2d12"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  aurora_curtain: {
  "id": "aurora_curtain",
  "name": "Aurora Curtain",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#67e8f9",
    "#3b82f6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  black_ice: {
  "id": "black_ice",
  "name": "Black Ice",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#334155",
    "#111827"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  bubblegum_legacy: {
  "id": "bubblegum_legacy",
  "name": "Bubblegum (Legacy)",
  "tier": "rare",
  "source": "inspiration",
  "kind": "gradient",
  "colors": [
    "#f472b6",
    "#fbcfe8"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "new"
},

  cloud_puff: {
  "id": "cloud_puff",
  "name": "Cloud Puff",
  "tier": "rare",
  "source": "production",
  "kind": "pattern",
  "colors": [
    "#A9D8FF",
    "#1E3A8A"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  confetti: {
  "id": "confetti",
  "name": "Confetti",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#FEF3C7",
    "#FDE68A"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  crevasse_light: {
  "id": "crevasse_light",
  "name": "Crevasse Light",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#93c5fd",
    "#64748b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  deep_dark_cave: {
  "id": "deep_dark_cave",
  "name": "Deep Dark Cave",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#0ea5e9",
    "#312e81"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  desert_varnish: {
  "id": "desert_varnish",
  "name": "Desert Varnish",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#a14a2a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  dune_surge: {
  "id": "dune_surge",
  "name": "Dune Surge",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fde68a",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ember_rim: {
  "id": "ember_rim",
  "name": "Ember Rim",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#ea580c",
    "#b45309"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  fault_glow: {
  "id": "fault_glow",
  "name": "Fault Glow",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#6b7280",
    "#374151"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  forge_heat: {
  "id": "forge_heat",
  "name": "Forge Heat",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#92400e",
    "#d97706"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  forge_rune: {
  "id": "forge_rune",
  "name": "Forge Rune",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#332b28"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  frost_fern: {
  "id": "frost_fern",
  "name": "Frost Fern",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#cfeff8"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  grass_run: {
  "id": "grass_run",
  "name": "Grass Run",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#c9d66c",
    "#f2f6c6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  gravity_well: {
  "id": "gravity_well",
  "name": "Gravity Well",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#0b1026",
    "#111827"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  honeycomb: {
  "id": "honeycomb",
  "name": "Honeycomb",
  "tier": "rare",
  "source": "production",
  "kind": "pattern",
  "colors": [
    "#FFD24A",
    "#92400E"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  kelp_curl: {
  "id": "kelp_curl",
  "name": "Kelp Curl",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#267a6f"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  monsoon_sheet: {
  "id": "monsoon_sheet",
  "name": "Monsoon Sheet",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#60a5fa",
    "#1e40af"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  moonlit_pool: {
  "id": "moonlit_pool",
  "name": "Moonlit Pool",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#1e293b",
    "#e2e8f0"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  moonlit_pool_enhanced: {
  "id": "moonlit_pool_enhanced",
  "name": "Moonlit Pool Enhanced",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#1e293b",
    "#e2e8f0"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  moss_quilt: {
  "id": "moss_quilt",
  "name": "Moss Quilt",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#2e7d5a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  moss_quilt_enhanced: {
  "id": "moss_quilt_enhanced",
  "name": "Moss Quilt Enhanced",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#2e7d5a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  never_ending_cave: {
  "id": "never_ending_cave",
  "name": "Never-Ending Cave",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#475569",
    "#1f2937"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ocean_drift: {
  "id": "ocean_drift",
  "name": "Ocean Drift",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#67e8f9",
    "#0ea5e9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ocean_drift_enhanced: {
  "id": "ocean_drift_enhanced",
  "name": "Ocean Drift Enhanced",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#67e8f9",
    "#0ea5e9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  pebble: {
  "id": "pebble",
  "name": "Pebble",
  "tier": "rare",
  "source": "production",
  "kind": "pattern",
  "colors": [
    "#E9D8B5",
    "#9D8057"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  polar_crown: {
  "id": "polar_crown",
  "name": "Polar Crown",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#86c5ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  polka_mint: {
  "id": "polka_mint",
  "name": "Polka Mint",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#B6E3B6",
    "#FFFFFF"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  polka_mint_enhanced: {
  "id": "polka_mint_enhanced",
  "name": "Polka Mint Enhanced",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#B6E3B6",
    "#FFFFFF"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  prism_mist: {
  "id": "prism_mist",
  "name": "Prism Mist",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#94a3b8",
    "#64748b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  quench_mist_inspiration: {
  "id": "quench_mist_inspiration",
  "name": "Quench Mist",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#1f2937",
    "#0f172a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ripple: {
  "id": "ripple",
  "name": "Ripple",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#7FECD8",
    "#134E4A"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ripple_enhanced: {
  "id": "ripple_enhanced",
  "name": "Ripple Enhanced",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#7FECD8",
    "#134E4A"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  riptide_bowl: {
  "id": "riptide_bowl",
  "name": "Riptide Bowl",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#22d3ee",
    "#2563eb"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  rope_coil: {
  "id": "rope_coil",
  "name": "Rope Coil",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#c8a06d"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sandstorm_wall: {
  "id": "sandstorm_wall",
  "name": "Sandstorm Wall",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fde68a",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  solar_haze: {
  "id": "solar_haze",
  "name": "Solar Haze",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fde047",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  spooky_cave: {
  "id": "spooky_cave",
  "name": "Spooky Cave",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#4338ca",
    "#1e1b4b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sprinkles: {
  "id": "sprinkles",
  "name": "Sprinkles",
  "tier": "rare",
  "source": "production",
  "kind": "pattern",
  "colors": [
    "#F7FBFF",
    "#93C5FD"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  starlet: {
  "id": "starlet",
  "name": "Starlet",
  "tier": "rare",
  "source": "production",
  "kind": "pattern",
  "colors": [
    "#2A2F35",
    "#0B0E12"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  static_sheet: {
  "id": "static_sheet",
  "name": "Static Sheet",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#0f172a",
    "#1f2937"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  tangerine_legacy: {
  "id": "tangerine_legacy",
  "name": "Tangerine (Legacy)",
  "tier": "rare",
  "source": "inspiration",
  "kind": "gradient",
  "colors": [
    "#fb923c",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "new"
},

  thunder_shelf: {
  "id": "thunder_shelf",
  "name": "Thunder Shelf",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#06b6d4",
    "#0ea5e9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  vine_inlay: {
  "id": "vine_inlay",
  "name": "Vine Inlay",
  "tier": "rare",
  "source": "production",
  "kind": "solid",
  "colors": [
    "#907a5d"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  volcanic_glass: {
  "id": "volcanic_glass",
  "name": "Volcanic Glass",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#0f172a",
    "#111827"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  whirlpool_eye: {
  "id": "whirlpool_eye",
  "name": "Whirlpool Eye",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#14b8a6",
    "#0ea5e9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  whirlwind_edge: {
  "id": "whirlwind_edge",
  "name": "Whirlwind Edge",
  "tier": "rare",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#f3e8d7",
    "#fde68a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  acacia_shade: {
  "id": "acacia_shade",
  "name": "Acacia Shade",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#e0b45a",
    "#f7ddb0"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  acacia_shade_enhanced: {
  "id": "acacia_shade_enhanced",
  "name": "Acacia Shade Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#f59e0b",
    "#eab308",
    "#a16207"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  anvil_ember: {
  "id": "anvil_ember",
  "name": "Anvil Ember",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#151515",
    "#ff6a00"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  anvil_ember_enhanced: {
  "id": "anvil_ember_enhanced",
  "name": "Anvil Ember Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#92400e",
    "#b45309"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  aurora_legacy: {
  "id": "aurora_legacy",
  "name": "Aurora (Legacy)",
  "tier": "epic",
  "source": "inspiration",
  "kind": "animated",
  "colors": [
    "#22d3ee",
    "#22c55e",
    "#a78bfa"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "new"
},

  aurora_veil: {
  "id": "aurora_veil",
  "name": "Aurora Veil",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#43e0c6",
    "#b189ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  aurora_veil_enhanced: {
  "id": "aurora_veil_enhanced",
  "name": "Aurora Veil Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#43e0c6",
    "#b189ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  aurora_veil_plus: {
  "id": "aurora_veil_plus",
  "name": "Aurora Veil+",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#43e0c6",
    "#b189ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  aurora_veil_plus_enhanced: {
  "id": "aurora_veil_plus_enhanced",
  "name": "Aurora Veil+ Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#43e0c6",
    "#b189ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  billboard_blink: {
  "id": "billboard_blink",
  "name": "Billboard Blink",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#312e81",
    "#1e1b4b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  billboard_blink_enhanced: {
  "id": "billboard_blink_enhanced",
  "name": "Billboard Blink Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#312e81",
    "#1e1b4b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  biolume_veil_enhanced: {
  "id": "biolume_veil_enhanced",
  "name": "Biolume Veil Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#0ea5e9",
    "#bae6fd"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  bog_bubble: {
  "id": "bog_bubble",
  "name": "Bog Bubble",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#16a34a",
    "#065f46"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  bog_bubble_enhanced: {
  "id": "bog_bubble_enhanced",
  "name": "Bog Bubble Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#16a34a",
    "#065f46"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  bubble_rise: {
  "id": "bubble_rise",
  "name": "Bubble Rise",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#6DDAD3",
    "#46C0B7",
    "#0F3431"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  canopy_lantern: {
  "id": "canopy_lantern",
  "name": "Canopy Lantern",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#207a4f",
    "#2ea271"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  canopy_lantern_enhanced: {
  "id": "canopy_lantern_enhanced",
  "name": "Canopy Lantern Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#16a34a",
    "#166534"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  canyon_shade_enhanced: {
  "id": "canyon_shade_enhanced",
  "name": "Canyon Shade Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#a14a2a",
    "#d67b4d"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  coral_chorus: {
  "id": "coral_chorus",
  "name": "Coral Chorus",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#ff7e6b",
    "#2fd3c9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  coral_chorus_enhanced: {
  "id": "coral_chorus_enhanced",
  "name": "Coral Chorus Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#60a5fa",
    "#a7f3d0"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  dune_drift: {
  "id": "dune_drift",
  "name": "Dune Drift",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fde68a",
    "#fbbf24",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  dune_drift_enhanced: {
  "id": "dune_drift_enhanced",
  "name": "Dune Drift Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fde68a",
    "#fbbf24",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  echo_rune_enhanced: {
  "id": "echo_rune_enhanced",
  "name": "Echo Rune Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#6a5d4a",
    "#d9c7a6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ember_bed: {
  "id": "ember_bed",
  "name": "Ember Bed",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#dc2626",
    "#fecaca",
    "#7f1d1d"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ember_bed_enhanced: {
  "id": "ember_bed_enhanced",
  "name": "Ember Bed Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#d97706",
    "#b45309"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  foundry_heatwave_enhanced: {
  "id": "foundry_heatwave_enhanced",
  "name": "Foundry Heatwave Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#151515",
    "#ff6a00"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  frog_chorus_enhanced: {
  "id": "frog_chorus_enhanced",
  "name": "Frog Chorus Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#22c55e",
    "#16a34a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  frost_breath: {
  "id": "frost_breath",
  "name": "Frost Breath",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#e0f2fe",
    "#f0f9ff",
    "#0c4a6e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  frost_breath_enhanced: {
  "id": "frost_breath_enhanced",
  "name": "Frost Breath Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#94a3b8",
    "#cbd5e1"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  geode_core: {
  "id": "geode_core",
  "name": "Geode Core",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#a78bfa",
    "#60a5fa"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  geode_core_enhanced: {
  "id": "geode_core_enhanced",
  "name": "Geode Core Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#a78bfa",
    "#60a5fa"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  glacier: {
  "id": "glacier",
  "name": "Glacier",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#f0f9ff",
    "#0ea5e9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  glacier_enhanced: {
  "id": "glacier_enhanced",
  "name": "Glacier Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#f0f9ff",
    "#0ea5e9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  glyph_bloom: {
  "id": "glyph_bloom",
  "name": "Glyph Bloom",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#6a5d4a",
    "#d9c7a6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  glyph_bloom_enhanced: {
  "id": "glyph_bloom_enhanced",
  "name": "Glyph Bloom Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#c7a875",
    "#a68a56"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  harbor_wake_enhanced: {
  "id": "harbor_wake_enhanced",
  "name": "Harbor Wake Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#0ea5e9",
    "#bae6fd"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  haystack: {
  "id": "haystack",
  "name": "Haystack",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fde68a",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  haystack_enhanced: {
  "id": "haystack_enhanced",
  "name": "Haystack Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fde68a",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  lava_legacy: {
  "id": "lava_legacy",
  "name": "Lava (Legacy)",
  "tier": "epic",
  "source": "inspiration",
  "kind": "animated",
  "colors": [
    "#ef4444",
    "#f97316",
    "#fbbf24"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "new"
},

  lava_flow: {
  "id": "lava_flow",
  "name": "Lava Flow",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#3A1D0E",
    "#FFF0DD",
    "#dc2626",
    "#dc2626"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  lava_flow_enhanced: {
  "id": "lava_flow_enhanced",
  "name": "Lava Flow Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#3A1D0E",
    "#FFF0DD",
    "#dc2626",
    "#dc2626"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  lighthouse_wink: {
  "id": "lighthouse_wink",
  "name": "Lighthouse Wink",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#5a82b8",
    "#dbe8ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  lighthouse_wink_enhanced: {
  "id": "lighthouse_wink_enhanced",
  "name": "Lighthouse Wink Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#93c5fd",
    "#60a5fa"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  magma_vein: {
  "id": "magma_vein",
  "name": "Magma Vein",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#7f1d1d",
    "#f97316"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  magma_vein_enhanced: {
  "id": "magma_vein_enhanced",
  "name": "Magma Vein Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#f59e0b",
    "#ea580c",
    "#7c2d12"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  mirage_enhanced: {
  "id": "mirage_enhanced",
  "name": "Mirage Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#fde68a",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  observatory_drift_enhanced: {
  "id": "observatory_drift_enhanced",
  "name": "Observatory Drift Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#2fd2ff",
    "#6a79ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ocean_anim: {
  "id": "ocean_anim",
  "name": "Ocean",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#0ea5e9",
    "#bae6fd"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  orchard_breeze: {
  "id": "orchard_breeze",
  "name": "Orchard Breeze",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#22c55e",
    "#16a34a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  orchard_breeze_enhanced: {
  "id": "orchard_breeze_enhanced",
  "name": "Orchard Breeze Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#22c55e",
    "#16a34a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  pearl_whisper: {
  "id": "pearl_whisper",
  "name": "Pearl Whisper",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#70c6c0",
    "#f2f7ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  pearl_whisper_enhanced: {
  "id": "pearl_whisper_enhanced",
  "name": "Pearl Whisper Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#e5e7eb",
    "#cbd5e1",
    "#f1f5f9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  rainbow_arc: {
  "id": "rainbow_arc",
  "name": "Rainbow Arc",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fca5a5",
    "#fcd34d",
    "#86efac",
    "#93c5fd",
    "#c4b5fd"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  rainbow_arc_enhanced: {
  "id": "rainbow_arc_enhanced",
  "name": "Rainbow Arc Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fca5a5",
    "#fcd34d",
    "#86efac",
    "#93c5fd",
    "#c4b5fd"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  redwall_glow: {
  "id": "redwall_glow",
  "name": "Redwall Glow",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#b3562e",
    "#d67b4d"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  redwall_glow_enhanced: {
  "id": "redwall_glow_enhanced",
  "name": "Redwall Glow Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#b91c1c",
    "#d97706"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  reef_bloom_enhanced: {
  "id": "reef_bloom_enhanced",
  "name": "Reef Bloom Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#ff7e6b",
    "#2fd3c9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  savanna_mirage_enhanced: {
  "id": "savanna_mirage_enhanced",
  "name": "Savanna Mirage Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#fde68a",
    "#f59e0b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  snow_lantern: {
  "id": "snow_lantern",
  "name": "Snow Lantern",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#9fd3e6",
    "#eaf7ff"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  snow_lantern_enhanced: {
  "id": "snow_lantern_enhanced",
  "name": "Snow Lantern Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#dbeafe",
    "#f1f5f9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  solar_flare: {
  "id": "solar_flare",
  "name": "Solar Flare",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#f59e0b",
    "#92400e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  stalactite_drip: {
  "id": "stalactite_drip",
  "name": "Stalactite Drip",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#64748b",
    "#94a3b8"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  stalactite_drip_enhanced: {
  "id": "stalactite_drip_enhanced",
  "name": "Stalactite Drip Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#64748b",
    "#94a3b8"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  subway_spark: {
  "id": "subway_spark",
  "name": "Subway Spark",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#334155",
    "#1f2937"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  subway_spark_enhanced: {
  "id": "subway_spark_enhanced",
  "name": "Subway Spark Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#334155",
    "#1f2937"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sunshower: {
  "id": "sunshower",
  "name": "Sunshower",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#bae6fd",
    "#fde68a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  sunshower_enhanced: {
  "id": "sunshower_enhanced",
  "name": "Sunshower Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#bae6fd",
    "#fde68a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  temple_incense_enhanced: {
  "id": "temple_incense_enhanced",
  "name": "Temple Incense Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#6a5d4a",
    "#d9c7a6"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  the_fizz: {
  "id": "the_fizz",
  "name": "The Fizz",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#BDEBFF",
    "#93DBFF"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  tundra_halo_enhanced: {
  "id": "tundra_halo_enhanced",
  "name": "Tundra Halo Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#86c5ff",
    "#e0f2fe"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  void_walker: {
  "id": "void_walker",
  "name": "Void Walker",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#0f0f23",
    "#1e1b4b"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  will_o_glow: {
  "id": "will_o_glow",
  "name": "Will-o-Glow",
  "tier": "epic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#0E1C14",
    "#F3FFF7"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  willow_glow: {
  "id": "willow_glow",
  "name": "Willow Glow",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#22c55e",
    "#16a34a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  willow_glow_enhanced: {
  "id": "willow_glow_enhanced",
  "name": "Willow Glow Enhanced",
  "tier": "epic",
  "source": "production",
  "kind": "gradient",
  "colors": [
    "#22c55e",
    "#16a34a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  black_hole: {
  "id": "black_hole",
  "name": "Black Hole",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#000000",
    "#1a1a2e",
    "#16213e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  black_hole_2: {
  "id": "black_hole_2",
  "name": "Black Hole 2",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#000000",
    "#1a1a2e",
    "#16213e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  black_hole_3: {
  "id": "black_hole_3",
  "name": "Black Hole 3",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#000000",
    "#1a1a2e",
    "#16213e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  black_hole_4: {
  "id": "black_hole_4",
  "name": "Black Hole 4",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#000000",
    "#1a1a2e",
    "#16213e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  black_hole_5: {
  "id": "black_hole_5",
  "name": "Black Hole 5",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#000000",
    "#1a1a2e",
    "#16213e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  cosmic: {
  "id": "cosmic",
  "name": "Cosmic",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#000000",
    "#1a1a2e",
    "#16213e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  galaxy_swirl: {
  "id": "galaxy_swirl",
  "name": "Galaxy Swirl",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#6a6bd6",
    "#3443a3",
    "#1a2454"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  infinite_money_glitch: {
  "id": "infinite_money_glitch",
  "name": "Infinite Money Glitch",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#fde047",
    "#92400e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  ionosong: {
  "id": "ionosong",
  "name": "Ionōsong",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#2fd2ff",
    "#6a79ff",
    "#121842"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  nebula: {
  "id": "nebula",
  "name": "Nebula",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#5b2d8f",
    "#1b1e4b",
    "#0f1530"
  ],
  "base": {
    "fill": "#1e1b4b",
    "stroke": "#0f172a",
    "shine": "#c7d2fe"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "deep_space_parallax",
  "migratedFrom": "old"
},

  nebula_legacy: {
  "id": "nebula_legacy",
  "name": "Nebula (Legacy)",
  "tier": "mythic",
  "source": "inspiration",
  "kind": "animated",
  "colors": [
    "#6d28d9",
    "#7c3aed",
    "#0ea5e9"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "new"
},

  phoenix_heart: {
  "id": "phoenix_heart",
  "name": "Phoenix Heart",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#ff7a3c",
    "#d12525",
    "#571616"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  portal: {
  "id": "portal",
  "name": "Portal",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#000000",
    "#1a1a2e",
    "#16213e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  star_parade: {
  "id": "star_parade",
  "name": "Star Parade",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#0f3d4b",
    "#062a36",
    "#08202a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  synthwave: {
  "id": "synthwave",
  "name": "Synthwave",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#7a3cff",
    "#ff4d6d",
    "#2c0c3a"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
},

  vertigo: {
  "id": "vertigo",
  "name": "Vertigo",
  "tier": "mythic",
  "source": "production",
  "kind": "animated",
  "colors": [
    "#000000",
    "#1a1a2e",
    "#16213e"
  ],
  "base": {
    "fill": "#9ca3af",
    "stroke": "#0b0f17",
    "shine": "#ffffff"
  },
  "pattern": {
    "type": "flat",
    "colors": [
      "#9ca3af"
    ]
  },
  "anim": "none",
  "migratedFrom": "old"
}
};

export default SKINS;
